### ISSUE TITLE
PII_Salt issue when creating a new user

### ISSUE THREAD

**Issue by sshivaji** [waqasbhatti/authnzerver#15]
Stacktrace:

authnzerver_1    | [I 200706 09:12:11 web:2246] 200 POST / (172.31.0.16) 1740.56ms
authnzerver_1    | [E 200706 09:17:38 handlers:292] Failed to understand request.
authnzerver_1    |     authnzerver.external.futures37.process._RemoteTraceback: 
authnzerver_1    |     """
authnzerver_1    |     Traceback (most recent call last):
authnzerver_1    |       File "/home/authnzerver/authnzerver/external/futures37/process.py", line 246, in _process_worker
authnzerver_1    |         r = call_item.fn(*call_item.args, **call_item.kwargs)
authnzerver_1    |       File "/home/authnzerver/authnzerver/actions/user.py", line 994, in create_new_user
authnzerver_1    |         pii_hash(rows['user_id'],payload['pii_salt']))
authnzerver_1    |     TypeError: 'NoneType' object is not subscriptable
authnzerver_1    |     """
authnzerver_1    |     
authnzerver_1    |     The above exception was the direct cause of the following exception:
authnzerver_1    |     
authnzerver_1    |     Traceback (most recent call last):
authnzerver_1    |       File "/home/authnzerver/authnzerver/handlers.py", line 213, in post
authnzerver_1    |         response = await loop.run_in_executor(
authnzerver_1    |     TypeError: 'NoneType' object is not subscriptable
authnzerver_1    | [W 200706 09:17:38 web:2246] 400 POST / (172.31.0.16) 104.35ms
authnzerver_1    | [E 200706 09:21:12 handlers:292] Failed to understand request.
authnzerver_1    |     authnzerver.external.futures37.process._RemoteTraceback: 
authnzerver_1    |     """
authnzerver_1    |     Traceback (most recent call last):
authnzerver_1    |       File "/home/authnzerver/authnzerver/external/futures37/process.py", line 246, in _process_worker
authnzerver_1    |         r = call_item.fn(*call_item.args, **call_item.kwargs)
authnzerver_1    |       File "/home/authnzerver/authnzerver/actions/user.py", line 994, in create_new_user
authnzerver_1    |         pii_hash(rows['user_id'],payload['pii_salt']))
authnzerver_1    |     TypeError: 'NoneType' object is not subscriptable
authnzerver_1    |     """
authnzerver_1    |     
authnzerver_1    |     The above exception was the direct cause of the following exception:
authnzerver_1    |     
authnzerver_1    |     Traceback (most recent call last):
authnzerver_1    |       File "/home/authnzerver/authnzerver/handlers.py", line 213, in post
authnzerver_1    |         response = await loop.run_in_executor(
authnzerver_1    |     TypeError: 'NoneType' object is not subscriptable
authnzerver_1    | [W 200706 09:21:12 web:2246] 400 POST / (172.31.0.16) 90.67ms

**Comment by waqasbhatti** [comment]
This is probably happening because the DB schema has changed for authnzerver. There's a new `extra_info` column in the `users` table. You'll have to rebuild the DB from scratch, I'm afraid, since there aren't any migration scripts for authnzerver yet.

The fix is to remove `.authdb.sqlite*` from the authnzerver base directory, shut down authnzerver and let it regenerate the DB on the next restart.

In Docker:

```
docker-compose exec authnzerver bash
cd basedir
rm -fv .authdb.sqlite*
```

Then restart the authnzerver container:

```
docker-compose restart authnzerver
```

It will regenerate its DB with the new schema.
